{{- range $ns, $nsParams := .Values.instances }}
{{- range $app, $params := $nsParams.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app }}
  namespace: {{ $ns }}
  labels:
    app: {{ $app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $app }}
  template:
    metadata:
      labels:
        app: {{ $app }}
      annotations:
        revision: {{ $.Release.Revision | quote }}
    spec:
      containers:
        - name: {{ $app }}
          image: {{ $.Values.image }}
          ports:
            - containerPort: {{ $.Values.podPort }}
          securityContext:
            {{- $.Values.securityContext | toYaml | nindent 12 }}
          resources:
            {{- $.Values.resources | toYaml | nindent 12 }}
          {{- if (($params).hosts) }}
            {{- $listHosts := "" }}
            {{- range $addr := $params.hosts }}
              {{- if ne (len $listHosts) 0 }}
                {{- $listHosts = printf "%s;" $listHosts }}
              {{- end }}
              {{/* TODO: How to specify external link ? */}}
              {{- $listHosts = printf "%shttp://%s:%s/ping" $listHosts $addr ($.Values.servicePort | toString) }}
            {{- end }}
          env:
            - name: HOSTS
              value: {{ $listHosts }}
            - name: LISTEN_ADDR
              value: "{{ $.Values.podListenAddress }}:{{ $.Values.podPort }}"
          {{- end }}

{{- end }}
{{- end }}
