{{- range $ns, $nsParams := .Values.instances }}
{{- if eq $nsParams.managed true }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    istio-injection: {{ $nsParams.istioInjection | default false | quote }}
spec:
  finalizers:
    - kubernetes

{{- end }}
{{- end }}
