{{- range $ns, $nsParams := .Values.instances }}
{{- range $app, $params := $nsParams.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app }}
  namespace: {{ $ns }}
spec:
  selector:
    app: {{ $app }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ $.Values.servicePort }}
      targetPort: {{ $.Values.podPort }}

{{- end }}
{{- end }}
