{{- range $ns, $instances := .Values.instances }}
{{- range $instance, $params := $instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $instance }}
  namespace: {{ $ns }}
spec:
  selector:
    app: {{ $instance }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ $.Values.servicePort }}
      targetPort: {{ $.Values.podPort }}

{{- end }}
{{- end }}
