---
image: "yuriiashutkin/web-app:1.7.0-scratch"
servicePort: 4000
podPort: 8080
podListenAddress: "0.0.0.0"

#securityContext:
#  runAsGroup: 0
#  runAsUser: 0
#  readOnlyRootFilesystem: false

securityContext:
  runAsGroup: 2000
  runAsUser: 2000
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 32Mi

instances:
  ns-1:
    managed: true
    istioInjection: disabled
    apps:
      myapp:
        hosts:
          - webapp.ns-2.svc.cluster.local
    network:
      inbound:
        - service: myapp
          from:
            - service: webapp
              namespace: ns-2
      outbound:
        - service: myapp
          to:
            - service: webapp
              namespace: ns-2

  ns-2:
    managed: true
    istioInjection: disabled
    apps:
      webapp:
        hosts:
          - myapp.ns-1.svc.cluster.local
    network:
      inbound:
        - service: webapp
          from:
            - service: myapp
              namespace: ns-1
      outbound:
        - service: webapp
          to:
            - service: myapp
              namespace: ns-1
