---
image: "yuriiashutkin/web-app:1.4.0-scratch"
servicePort: 4000
podPort: 8080

securityContext:
  runAsGroup: 2000
  runAsUser: 2000
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

instances:
  first:
    managed: true
    apps:
      webapp:
        hosts:
          - app.svc
          - webapp.first.svc.cluster.local
      app: {}
  second:
    managed: true
    apps:
      webapp: {}
